### ISSUE TITLE
点击全屏播放闪退

### ISSUE THREAD

**Issue by rubnet** [ekibun/VideoPlayer#1]
已卸载

**Comment by ekibun** [comment]
。。我刚改完

**Comment by rubnet** [comment]
考虑一下把这个项目的rule拿来用？
https://github.com/qiusunshine/movienow

**Comment by ekibun** [comment]
不如js方便啊。。。

**Comment by rubnet** [comment]
我看了项目的代码也是用Mozilla的js引擎解析的

**Comment by ekibun** [comment]
再套一层没意义啊
而且弹幕和播放地址也不是css选择器能抓出来的呀。。

**Comment by rubnet** [comment]
不一定要弹幕，有视频就行，上面项目的rules是各种视频站的css提取播放链接的集合,视频源地址还要用他写的代码嗅探…

**Comment by ekibun** [comment]
获取视频信息留空会默认嗅探剧集信息返回的url，我还是觉得css不如js好用，解析起来也麻烦。。
其实是有个webview.load方法来抓视频的，但是太麻烦了，参考https://github.com/ekibun/VideoPlayer/blob/c10fe055634bee9caa513dbbe26e61ea560df14f/app/src/main/java/soko/ekibun/videoplayer/JsEngine.kt#L87
